In [32]:
%reset    #돌렸던거 다시 reset시키고 다시한다

Once deleted, variables cannot be recovered. Proceed (y/[n])? y

In [33]:
import numpy as np
import pandas as pd

In [34]:
moonsu1=pd.read_csv('C:/Users/korewa/Desktop/SPMS_Data_20181206/9421984_201709.csv')  #pandas로 csv read시킨다

In [36]:
moonsu1.columns   #이렇게하면 어떤 변수들이 있는지 알 수 있다.

Index(['Timestamp', 'Validity', 'Latitude', 'Longitude', 'Speed over Ground',
       'Longitudinal Ground Speed', 'Longitudinal Water Speed',
       'Course over Ground', 'Heading', 'Rudder Angle', 'Sea Depth',
       'Relative Wind Speed', 'Relative Wind Direction', 'True Wind Speed',
       'True Wind Direction', 'Forward Draft', 'Afterward Draft', 'Roll',
       'Pitch', 'Propeller RPM', 'Shaft Torque', 'Shaft Thrust', 'Shaft Power',
       'ME FOC', 'Break Horse Power', 'Slip', 'Seawater Temperature',
       'Air Temperature', 'Air Pressure', 'True Current Speed',
       'True Current Direction', 'Total Wave Height', 'Total Wave Direction',
       'Total Wave Period', 'Swell Wave Height', 'Swell Wave Direction',
       'Swell Wave Period', 'Wind Wave Height', 'Wind Wave Direction',
       'Wind Wave Period', 'Voyage', 'From', 'To', 'Status'],
      dtype='object')

In [ ]:
def moonsu1 (x):
    y=x+x
    return y

In [37]:
moonsu1.shape   #table이 어떻게 생겼는 지 알 수 있다.

(28224, 44)

In [125]:
a=np.abs(np.diff(moonsu1["Propeller RPM"].values)).tolist()    #numpy를 쓸때 ()는 연속으로 쓸 때 쓰는거 같고 []는 인덱싱에 쓴다 tolist()는 
#리스트로 만들어주는 함수를 뜻하는 것이다.
moonsu1['increasing'] =[np.nan] + a  #a 에다가 맨앞 행에 nan을 하나 집어 넣는다 이유는 나중에 비교할 때 행의 개수를 맞춰 주어야 연산이 가능
# 하기 때문

In [126]:
a=np.abs(np.diff(moonsu1["Propeller RPM"].values)).tolist()
moonsu1['increasing'] = a + [np.nan] #a 맨마지막에다가 nan을 집어넣는다

In [120]:
np.array([[1,2,3],[3,4,5]])[:,0]

array([1, 3])

In [122]:
moonsu1.iloc[:,0]  #iloc는 정수형 접근만 가능 하다 but loc는 다 가능

Timestamp
2017-09-27 17:24:04    2017-09-27 17:24:04
2017-09-27 17:24:14    2017-09-27 17:24:14
2017-09-27 17:24:24    2017-09-27 17:24:24
2017-09-27 17:24:34    2017-09-27 17:24:34
2017-09-27 17:24:44    2017-09-27 17:24:44
2017-09-27 17:24:54    2017-09-27 17:24:54
2017-09-27 17:25:04    2017-09-27 17:25:04
2017-09-27 17:25:14    2017-09-27 17:25:14
2017-09-27 17:25:24    2017-09-27 17:25:24
2017-09-27 17:25:34    2017-09-27 17:25:34
2017-09-27 17:25:44    2017-09-27 17:25:44
2017-09-27 17:25:54    2017-09-27 17:25:54
2017-09-27 17:26:04    2017-09-27 17:26:04
2017-09-27 17:26:14    2017-09-27 17:26:14
2017-09-27 17:26:24    2017-09-27 17:26:24
2017-09-27 17:26:34    2017-09-27 17:26:34
2017-09-27 17:26:44    2017-09-27 17:26:44
2017-09-27 17:26:54    2017-09-27 17:26:54
2017-09-27 17:27:04    2017-09-27 17:27:04
2017-09-27 17:27:14    2017-09-27 17:27:14
2017-09-27 17:27:24    2017-09-27 17:27:24
2017-09-27 17:27:34    2017-09-27 17:27:34
2017-09-27 17:27:44    2017-09-27 17:27:44
2017-09-27 17:27:54    2017-09-27 17:27:54
2017-09-27 17:28:04    2017-09-27 17:28:04
2017-09-27 17:28:14    2017-09-27 17:28:14
2017-09-27 17:28:24    2017-09-27 17:28:24
2017-09-27 17:28:34    2017-09-27 17:28:34
2017-09-27 17:28:44    2017-09-27 17:28:44
2017-09-27 17:28:54    2017-09-27 17:28:54
                              ...
2017-09-30 23:55:05    2017-09-30 23:55:05
2017-09-30 23:55:15    2017-09-30 23:55:15
2017-09-30 23:55:25    2017-09-30 23:55:25
2017-09-30 23:55:35    2017-09-30 23:55:35
2017-09-30 23:55:45    2017-09-30 23:55:45
2017-09-30 23:55:55    2017-09-30 23:55:55
2017-09-30 23:56:05    2017-09-30 23:56:05
2017-09-30 23:56:15    2017-09-30 23:56:15
2017-09-30 23:56:25    2017-09-30 23:56:25
2017-09-30 23:56:35    2017-09-30 23:56:35
2017-09-30 23:56:45    2017-09-30 23:56:45
2017-09-30 23:56:55    2017-09-30 23:56:55
2017-09-30 23:57:05    2017-09-30 23:57:05
2017-09-30 23:57:15    2017-09-30 23:57:15
2017-09-30 23:57:25    2017-09-30 23:57:25
2017-09-30 23:57:35    2017-09-30 23:57:35
2017-09-30 23:57:45    2017-09-30 23:57:45
2017-09-30 23:57:55    2017-09-30 23:57:55
2017-09-30 23:58:05    2017-09-30 23:58:05
2017-09-30 23:58:15    2017-09-30 23:58:15
2017-09-30 23:58:25    2017-09-30 23:58:25
2017-09-30 23:58:35    2017-09-30 23:58:35
2017-09-30 23:58:45    2017-09-30 23:58:45
2017-09-30 23:58:55    2017-09-30 23:58:55
2017-09-30 23:59:05    2017-09-30 23:59:05
2017-09-30 23:59:15    2017-09-30 23:59:15
2017-09-30 23:59:25    2017-09-30 23:59:25
2017-09-30 23:59:35    2017-09-30 23:59:35
2017-09-30 23:59:45    2017-09-30 23:59:45
2017-09-30 23:59:55    2017-09-30 23:59:55
Name: Timestamp, Length: 28224, dtype: object

In [118]:
moonsu1[moonsu1['a'] == True]["b"]

Timestamp
2017-09-27 17:24:04    25.5146
2017-09-27 17:24:14    25.5151
2017-09-27 17:24:24    25.5157
2017-09-27 17:24:34    25.5163
2017-09-27 17:24:44    25.5168
2017-09-27 17:24:54    25.5174
2017-09-27 17:25:04    25.5180
2017-09-27 17:25:14    25.5185
2017-09-27 17:25:24    25.5191
2017-09-27 17:25:34    25.5197
2017-09-27 17:25:44    25.5202
2017-09-27 17:25:54    25.5208
2017-09-27 17:26:04    25.5213
2017-09-27 17:26:14    25.5219
2017-09-27 17:26:24    25.5225
2017-09-27 17:26:34    25.5230
2017-09-27 17:26:44    25.5236
2017-09-27 17:26:54    25.5241
2017-09-27 17:27:04    25.5247
2017-09-27 17:27:14    25.5253
2017-09-27 17:27:24    25.5259
2017-09-27 17:27:34    25.5264
2017-09-27 17:27:44    25.5270
2017-09-27 17:27:54    25.5275
2017-09-27 17:28:04    25.5281
2017-09-27 17:28:14    25.5286
2017-09-27 17:28:24    25.5292
2017-09-27 17:28:34    25.5297
2017-09-27 17:28:44    25.5303
2017-09-27 17:28:54    25.5308
                        ...
2017-09-30 23:55:05    27.3287
2017-09-30 23:55:15    27.3291
2017-09-30 23:55:25    27.3294
2017-09-30 23:55:35    27.3297
2017-09-30 23:55:45    27.3301
2017-09-30 23:55:55    27.3304
2017-09-30 23:56:05    27.3307
2017-09-30 23:56:15    27.3311
2017-09-30 23:56:25    27.3314
2017-09-30 23:56:35    27.3317
2017-09-30 23:56:45    27.3321
2017-09-30 23:56:55    27.3324
2017-09-30 23:57:05    27.3327
2017-09-30 23:57:15    27.3331
2017-09-30 23:57:25    27.3334
2017-09-30 23:57:35    27.3337
2017-09-30 23:57:45    27.3341
2017-09-30 23:57:55    27.3344
2017-09-30 23:58:05    27.3347
2017-09-30 23:58:15    27.3351
2017-09-30 23:58:25    27.3354
2017-09-30 23:58:35    27.3357
2017-09-30 23:58:45    27.3361
2017-09-30 23:58:55    27.3364
2017-09-30 23:59:05    27.3367
2017-09-30 23:59:15    27.3371
2017-09-30 23:59:25    27.3374
2017-09-30 23:59:35    27.3377
2017-09-30 23:59:45    27.3381
2017-09-30 23:59:55    27.3384
Name: Latitude, Length: 27456, dtype: float64

In [108]:
moonsu1.index = moonsu1['Timestamp']

In [40]:
moonsu1['Rate_Propeller RPM'] = moonsu1['Propeller RPM'].apply(lambda x : np.abs(x)*0.2)
#lamda가 뜻하는 바는
def moonsu1(x):
    return x*0.2
#와 같은 뜻이라고 한다    여기선 x를 절대값을 취해준다음에 0.2곱한 값을 뱉는 다는 뜻..  간단한 함수에 사용 가능

In [50]:
import datetime
def

In [49]:
moonsu1.loc[moonsu1['Rate_Propeller RPM'] < moonsu1['increasing']]['Timestamp']

5796      2017-09-28 9:32:20
5797      2017-09-28 9:32:30
5798      2017-09-28 9:32:40
5799      2017-09-28 9:32:50
5800      2017-09-28 9:33:00
5862      2017-09-28 9:43:21
5863      2017-09-28 9:43:31
7383     2017-09-28 13:57:17
7384     2017-09-28 13:57:27
7395     2017-09-28 13:59:17
7396     2017-09-28 13:59:27
7609     2017-09-28 14:35:00
8945     2017-09-28 18:17:54
8973     2017-09-28 18:22:34
9018     2017-09-28 18:30:05
9031     2017-09-28 18:32:15
9034     2017-09-28 18:32:45
9054     2017-09-28 18:36:05
9055     2017-09-28 18:36:15
9063     2017-09-28 18:37:35
9064     2017-09-28 18:37:45
9113     2017-09-28 18:45:56
9114     2017-09-28 18:46:05
9122     2017-09-28 18:47:25
9123     2017-09-28 18:47:36
9177     2017-09-28 18:56:36
9180     2017-09-28 18:57:06
9181     2017-09-28 18:57:16
9191     2017-09-28 18:58:56
9195     2017-09-28 18:59:37
9196     2017-09-28 18:59:47
9210     2017-09-28 19:02:07
9233     2017-09-28 19:05:57
9234     2017-09-28 19:06:07
9359     2017-09-28 19:26:58
9360     2017-09-28 19:27:08
9361     2017-09-28 19:27:18
18051    2017-09-29 19:39:50
18052    2017-09-29 19:40:00
18665    2017-09-29 21:22:16
18668    2017-09-29 21:22:46
18669    2017-09-29 21:22:56
18670    2017-09-29 21:23:06
18672    2017-09-29 21:23:26
18673    2017-09-29 21:23:36
18723    2017-09-29 21:31:57
18724    2017-09-29 21:32:07
18727    2017-09-29 21:32:37
18728    2017-09-29 21:32:47
18767    2017-09-29 21:39:17
18778    2017-09-29 21:41:07
18779    2017-09-29 21:41:17
18791    2017-09-29 21:43:17
18845    2017-09-29 21:52:18
18918    2017-09-29 22:04:29
Name: Timestamp, dtype: object

In [124]:
moonsu1.loc[moonsu1["a"]<0]['b']  #숫자 조건은 가능했지만
moonsu1.loc[moonsu1["a"]==True]['b']  #문자 조건은 가능하지 않았다  -> sas랑 다른 점  => True라고 쳐주면 bool로 인식하기 때문에
# 된다.

Timestamp
2017-09-27 17:24:04    59
2017-09-27 17:24:14    59
2017-09-27 17:24:24    59
2017-09-27 17:24:34    59
2017-09-27 17:24:44    59
2017-09-27 17:24:54    59
2017-09-27 17:25:04    59
2017-09-27 17:25:14    59
2017-09-27 17:25:24    59
2017-09-27 17:25:34    59
2017-09-27 17:25:44    59
2017-09-27 17:25:54    59
2017-09-27 17:26:04    59
2017-09-27 17:26:14    59
2017-09-27 17:26:24    59
2017-09-27 17:26:34    59
2017-09-27 17:26:44    59
2017-09-27 17:26:54    59
2017-09-27 17:27:04    59
2017-09-27 17:27:14    59
2017-09-27 17:27:24    59
2017-09-27 17:27:34    59
2017-09-27 17:27:44    59
2017-09-27 17:27:54    59
2017-09-27 17:28:04    59
2017-09-27 17:28:14    59
2017-09-27 17:28:24    59
2017-09-27 17:28:34    59
2017-09-27 17:28:44    59
2017-09-27 17:28:54    59
                       ..
2017-09-30 23:55:05    59
2017-09-30 23:55:15    59
2017-09-30 23:55:25    59
2017-09-30 23:55:35    59
2017-09-30 23:55:45    59
2017-09-30 23:55:55    59
2017-09-30 23:56:05    59
2017-09-30 23:56:15    59
2017-09-30 23:56:25    59
2017-09-30 23:56:35    59
2017-09-30 23:56:45    59
2017-09-30 23:56:55    59
2017-09-30 23:57:05    59
2017-09-30 23:57:15    59
2017-09-30 23:57:25    59
2017-09-30 23:57:35    59
2017-09-30 23:57:45    59
2017-09-30 23:57:55    59
2017-09-30 23:58:05    59
2017-09-30 23:58:15    59
2017-09-30 23:58:25    59
2017-09-30 23:58:35    59
2017-09-30 23:58:45    59
2017-09-30 23:58:55    59
2017-09-30 23:59:05    59
2017-09-30 23:59:15    59
2017-09-30 23:59:25    59
2017-09-30 23:59:35    59
2017-09-30 23:59:45    59
2017-09-30 23:59:55    59
Name: Voyage, Length: 27456, dtype: int64

In [100]:
moonsu1.loc[moonsu1["Validity"] < moonsu1["increasing"]]["increasing"]
#그냥 요런 느낌으로 항상 써라
moonsu1.loc[moonsu1['Rate_Propeller RPM'] < moonsu1['increasing']]['Timestamp']
#인덱싱은 앞은 행 뒤는 열이라고 전체 적으로 생각해도 될 것 같다.

5796      2017-09-28 9:32:20
5797      2017-09-28 9:32:30
5798      2017-09-28 9:32:40
5799      2017-09-28 9:32:50
5800      2017-09-28 9:33:00
5862      2017-09-28 9:43:21
5863      2017-09-28 9:43:31
7383     2017-09-28 13:57:17
7384     2017-09-28 13:57:27
7395     2017-09-28 13:59:17
7396     2017-09-28 13:59:27
7609     2017-09-28 14:35:00
8945     2017-09-28 18:17:54
8973     2017-09-28 18:22:34
9018     2017-09-28 18:30:05
9031     2017-09-28 18:32:15
9034     2017-09-28 18:32:45
9054     2017-09-28 18:36:05
9055     2017-09-28 18:36:15
9063     2017-09-28 18:37:35
9064     2017-09-28 18:37:45
9113     2017-09-28 18:45:56
9114     2017-09-28 18:46:05
9122     2017-09-28 18:47:25
9123     2017-09-28 18:47:36
9177     2017-09-28 18:56:36
9180     2017-09-28 18:57:06
9181     2017-09-28 18:57:16
9191     2017-09-28 18:58:56
9195     2017-09-28 18:59:37
9196     2017-09-28 18:59:47
9210     2017-09-28 19:02:07
9233     2017-09-28 19:05:57
9234     2017-09-28 19:06:07
9359     2017-09-28 19:26:58
9360     2017-09-28 19:27:08
9361     2017-09-28 19:27:18
18051    2017-09-29 19:39:50
18052    2017-09-29 19:40:00
18665    2017-09-29 21:22:16
18668    2017-09-29 21:22:46
18669    2017-09-29 21:22:56
18670    2017-09-29 21:23:06
18672    2017-09-29 21:23:26
18673    2017-09-29 21:23:36
18723    2017-09-29 21:31:57
18724    2017-09-29 21:32:07
18727    2017-09-29 21:32:37
18728    2017-09-29 21:32:47
18767    2017-09-29 21:39:17
18778    2017-09-29 21:41:07
18779    2017-09-29 21:41:17
18791    2017-09-29 21:43:17
18845    2017-09-29 21:52:18
18918    2017-09-29 22:04:29
Name: Timestamp, dtype: object

In [96]:
moonsu1.loc[moonsu1["Validity"] < moonsu1["increasing"]["increasing"]
#위에는 []를 쳐놨고 아래는 안쳐놨다 둘다 가능

SyntaxError: unexpected EOF while parsing (<ipython-input-96-046dc6e37491>, line 2)